# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: omiroshn <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/11 15:14:15 by omiroshn          #+#    #+#              #
#    Updated: 2019/10/11 15:14:16 by omiroshn         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = a.out
SOURCES = atom.ml carbon.ml copper.ml hydrogen.ml iron.ml oxygen.ml tin.ml main.ml
include OCamlMakefile
