RESULT = tic-tac-tic-tac-toe

SOURCES = source/TicTak.ml \
		source/SmallBoard.ml \
		source/BigBoard.ml \
		source/Game.ml \
		source/InputOutput.ml \
		source/GameLoop.ml \
		source/main.ml

OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)